# Generated by Django 6.0.3 on 2026-04-03 02:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloqueHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ramo', models.CharField(max_length=200)),
                ('sala', models.CharField(blank=True, max_length=100, null=True)),
                ('dia_semana', models.CharField(choices=[('MO', 'Lunes'), ('TU', 'Martes'), ('WE', 'Miércoles'), ('TH', 'Jueves'), ('FR', 'Viernes'), ('SA', 'Sábado')], max_length=2)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
