# Generated by Django 6.0.4 on 2026-04-09 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloquehorario',
            name='fecha',
            field=models.DateField(null=True),
        ),
    ]
